language: node_js
node_js:
  - node
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run docs
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  - provider: pages
    token: $GITHUB_TOKEN
    local_dir: docs
    keep_history: false
    edge: true
    on:
     branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_token: $NPM_API_TOKEN
    edge: true
    on:
      tags: true
      branch: master